In [1]:
pip install tensorflow

In [2]:
import tensorflow as tf
print(tf.__version__)

2.19.0


In [7]:
a = tf.constant(5)
print(a)

v=tf.constant([1,2,3,4])
print(v)

m=tf.constant([[1,2],[3,4]])
print(m)

t3 = tf.constant([
    [[1, 2], [3, 4]], [[5, 6], [7, 8]]
])
print(t3)


tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]], shape=(2, 2, 2), dtype=int32)


In [8]:
a=tf.constant([10,20,30])
b=tf.constant([50,60,70])
print(a+b)

tf.Tensor([ 60  80 100], shape=(3,), dtype=int32)


In [9]:
a=tf.constant([5,10,15])
b=tf.constant([6,7,8])
print(a-b)

tf.Tensor([-1  3  7], shape=(3,), dtype=int32)


In [10]:
a=tf.constant([5,10,15])
b=tf.constant([6,7,8])
print(a*b)

tf.Tensor([ 30  70 120], shape=(3,), dtype=int32)


In [11]:
a=tf.constant([5,10,15])
b=tf.constant([6,7,8])
print(a/b)

tf.Tensor([0.83333333 1.42857143 1.875     ], shape=(3,), dtype=float64)


In [12]:
a=tf.constant([5,10,15])
b=tf.constant(6)
print(pow(a,b))

tf.Tensor([   15625  1000000 11390625], shape=(3,), dtype=int32)


In [ ]:
# operations on scalor tensors
a=tf.constant(20)
b=tf.constant(5)
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(pow(a,b))

In [15]:
#operations on 3D tensors
a = tf.constant([
    [[1, 1], [1, 1]],
    [[2, 2], [2, 2]]
])

b = tf.constant([
    [[5, 5], [5, 5]],
    [[3, 3], [3, 3]]
])

print(a + b)
print(a-b)
print(a*b)
print(a/b)


tf.Tensor(
[[[6 6]
  [6 6]]

 [[5 5]
  [5 5]]], shape=(2, 2, 2), dtype=int32)
tf.Tensor(
[[[-4 -4]
  [-4 -4]]

 [[-1 -1]
  [-1 -1]]], shape=(2, 2, 2), dtype=int32)
tf.Tensor(
[[[5 5]
  [5 5]]

 [[6 6]
  [6 6]]], shape=(2, 2, 2), dtype=int32)
tf.Tensor(
[[[0.2        0.2       ]
  [0.2        0.2       ]]

 [[0.66666667 0.66666667]
  [0.66666667 0.66666667]]], shape=(2, 2, 2), dtype=float64)


In [16]:
import numpy as np
np_array=([[1,2,3],[4,5,6]])
tensor = tf.convert_to_tensor(np_array)
print(tensor)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
